import React from "react";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Favicon from '/public/favicon.ico';
import "./styles/_styles.scss";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: [
        {rel: 'icon', url: Favicon.src}
    ],
    metadataBase: new URL("https://example.com"),
    robots: {
        index: true,
        follow: true,
        googleBot: {
            index: true,
            follow: true,
            "max-video-preview": -1,
            "max-image-preview": "large",
            "max-snippet": -1,
        },
    },
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
     <html lang="en">
     <body className={inter.className}>{children}</body>
     </html>
    );
}
